"use strict";
const gookieCatalogue=[
{id:"wonder-chip",name:"Wonder Chip",subtitle:"Classic Chocolate Chip",description:"The cookie that started the wonder — golden, chunky and loaded with chocolate in every bite.",image:"wonder-chip.png"},
{id:"choco-loco",name:"Choco Loco",subtitle:"Milk Chocolate Chip",description:"A joyful chocolate overload for days when one kind of chocolate is simply not enough.",image:"choco-loco.png"},
{id:"dark-crush",name:"Dark Crush",subtitle:"Dark Chocolate & Sea Salt",description:"Deep cocoa, dark chocolate and a little sea salt for the perfect bold, balanced bite.",image:"dark-crush.png"},
{id:"red-bloom",name:"Red Bloom",subtitle:"Red Velvet",description:"Soft red velvet charm with creamy white chocolate woven through every chunky bite.",image:"red-bloom.png"},
{id:"matcha-matchy",name:"Matcha Matchy",subtitle:"Matcha & Macadamia",description:"Earthy matcha, creamy white chocolate and roasted macadamia in one very happy match.",image:"matcha-matchy.png"},
{id:"dream-cream",name:"Dream Cream",subtitle:"Cookies & Cream",description:"Chocolate cookie crumbs, creamy notes and the kind of comfort that disappears far too quickly.",image:"dream-cream.png"},
{id:"mallow-melt",name:"Mallow Melt",subtitle:"S'mores",description:"Toasty marshmallow comfort with chocolate and cookie goodness tucked into every bite.",image:"mallow-melt.png"},
{id:"biscoff-boom",name:"Biscoff Boom",subtitle:"Biscoff Filled",description:"Caramelised cookie flavour with a soft Biscoff centre that goes boom the moment you bite in.",image:"biscoff-boom.png"},
{id:"choki-chomp",name:"Choki Chomp",subtitle:"Chocolate Hazelnut Filled",description:"A playful chocolate-hazelnut centre wrapped inside a chunky cookie made for serious chomping.",image:"choki-chomp.png"},
{id:"coffee-kiss",name:"Coffee Kiss",subtitle:"Tiramisu Filled",description:"A gentle coffee kiss with creamy tiramisu-inspired flavour inside a soft, chunky cookie.",image:"coffee-kiss.png"},
{id:"monthly-wonder",name:"Monthly Wonder",subtitle:"Limited Monthly Flavour",description:"A new chunky wonder that changes with the month — here for a delicious time, not a long time.",image:"monthly-wonder.png"}
];
const gookieCollections=[
{id:"best-sellers",name:"Best-Seller Box",description:"The crowd favourites we would hand to anyone trying Gookie for the first time.",pool:["wonder-chip","dark-crush","matcha-matchy","biscoff-boom","choki-chomp","mallow-melt"]},
{id:"signature-cookies",name:"Signature Cookies",description:"A balanced mix that captures the full personality of Gookie.",pool:["wonder-chip","red-bloom","matcha-matchy","dream-cream","biscoff-boom","coffee-kiss"]},
{id:"full-wonder",name:"Full Wonder",description:"A little bit of everything, curated into one colourful box.",pool:gookieCatalogue.map(c=>c.id)},
{id:"full-mallow",name:"Full Mallow",description:"For the marshmallow lover who knows exactly what they want.",pool:["mallow-melt"]}
];
const $=id=>document.getElementById(id),body=document.body,pageOverlay=$("pageOverlay"),menuButton=$("menuButton"),cartButton=$("cartButton"),menuDrawer=$("menuDrawer"),cartDrawer=$("cartDrawer"),menuCloseButton=$("menuCloseButton"),cartCloseButton=$("cartCloseButton"),marqueeTrack=$("marqueeTrack"),cookieModal=$("cookieModal"),cookieModalClose=$("cookieModalClose"),modalCookieImage=$("modalCookieImage"),modalCookieSubtitle=$("modalCookieSubtitle"),modalCookieName=$("modalCookieName"),modalCookieDescription=$("modalCookieDescription"),getYourGookiesButton=$("getYourGookiesButton"),showBuildYourBox=$("showBuildYourBox"),showGookiesChoice=$("showGookiesChoice"),buildYourBoxSection=$("build-your-box"),gookiesChoiceSection=$("gookies-choice"),buildBoxSizeOptions=$("buildBoxSizeOptions"),buildSelectedBoxName=$("buildSelectedBoxName"),buildSelectedCount=$("buildSelectedCount"),buildBoxCapacity=$("buildBoxCapacity"),buildCookieSlots=$("buildCookieSlots"),buildBoxHelper=$("buildBoxHelper"),openFlavourSelector=$("openFlavourSelector"),flavourModal=$("flavourModal"),flavourModalClose=$("flavourModalClose"),flavourModalTitle=$("flavourModalTitle"),flavourSelectedCount=$("flavourSelectedCount"),flavourBoxCapacity=$("flavourBoxCapacity"),flavourNameList=$("flavourNameList"),saveFlavourSelection=$("saveFlavourSelection"),collectionGrid=$("collectionGrid"),gookieChoiceBoxArea=$("gookieChoiceBoxArea"),gookieChoiceSizeOptions=$("gookieChoiceSizeOptions"),gookieChoicePreview=$("gookieChoicePreview"),gookieChoiceTitle=$("gookieChoiceTitle"),gookieChoiceSlots=$("gookieChoiceSlots"),gookieChoiceSummary=$("gookieChoiceSummary"),reshuffleChoice=$("reshuffleChoice"),keepGookieChoice=$("keepGookieChoice"),cartCount=$("cartCount"),cartSelectedCount=$("cartSelectedCount"),cartEmptyState=$("cartEmptyState"),cartContent=$("cartContent"),cartOrderSummary=$("cartOrderSummary"),checkoutButton=$("checkoutButton");
let buildBoxSize=0,buildBoxName="",buildSelection=[],selectedCollection=null,gookieChoiceSize=0,gookieChoiceSelection=[],currentOrder=null;
const getCookieById=id=>gookieCatalogue.find(c=>c.id===id);
function openOverlay(){pageOverlay.hidden=false;requestAnimationFrame(()=>pageOverlay.classList.add("is-visible"));body.classList.add("no-scroll")}
function closeOverlayIfIdle(){if(document.querySelector(".drawer.is-open,.modal.is-open"))return;pageOverlay.classList.remove("is-visible");body.classList.remove("no-scroll");setTimeout(()=>pageOverlay.hidden=true,260)}
function scrollToSection(s){s.scrollIntoView({behavior:"smooth",block:"start"})}
function openDrawer(d,b){closeAllDrawers();d.classList.add("is-open");d.setAttribute("aria-hidden","false");b.setAttribute("aria-expanded","true");openOverlay()}
function closeDrawer(d){d.classList.remove("is-open");d.setAttribute("aria-hidden","true");menuButton.setAttribute("aria-expanded","false");cartButton.setAttribute("aria-expanded","false");closeOverlayIfIdle()}
function closeAllDrawers(){document.querySelectorAll(".drawer.is-open").forEach(d=>{d.classList.remove("is-open");d.setAttribute("aria-hidden","true")});menuButton.setAttribute("aria-expanded","false");cartButton.setAttribute("aria-expanded","false");closeOverlayIfIdle()}
function openModal(m){m.classList.add("is-open");m.setAttribute("aria-hidden","false");openOverlay()}
function closeModal(m){m.classList.remove("is-open");m.setAttribute("aria-hidden","true");closeOverlayIfIdle()}
function closeAllModals(){document.querySelectorAll(".modal.is-open").forEach(m=>{m.classList.remove("is-open");m.setAttribute("aria-hidden","true")});closeOverlayIfIdle()}
function createMarqueeCard(c){const b=document.createElement("button");b.className="marquee-card";b.type="button";b.innerHTML=`<span class="marquee-card-image"><img src="${c.image}" alt="${c.name}"></span><span class="marquee-card-copy"><small>${c.subtitle}</small><strong>${c.name}</strong></span>`;b.addEventListener("click",()=>{pauseMarquee();openCookieDetails(c)});return b}
function renderMarquee(){[...gookieCatalogue,...gookieCatalogue].forEach(c=>marqueeTrack.appendChild(createMarqueeCard(c)))}
const pauseMarquee=()=>marqueeTrack.classList.add("is-paused"),resumeMarquee=()=>marqueeTrack.classList.remove("is-paused");
function openCookieDetails(c){modalCookieImage.src=c.image;modalCookieImage.alt=c.name;modalCookieSubtitle.textContent=c.subtitle;modalCookieName.textContent=c.name;modalCookieDescription.textContent=c.description;openModal(cookieModal)}
function closeCookieDetails(resume=true){closeModal(cookieModal);if(resume)resumeMarquee()}
function showOrderSection(show,hide){hide.classList.add("is-hidden");show.classList.remove("is-hidden");setTimeout(()=>scrollToSection(show),20)}
function renderCookieSlots(container,capacity,selection){container.innerHTML="";for(let i=0;i<capacity;i++){const slot=document.createElement("div"),cookie=selection[i]?getCookieById(selection[i]):null;slot.className="cookie-slot";if(cookie){slot.classList.add("has-cookie");slot.innerHTML=`<img src="${cookie.image}" alt="${cookie.name}"><span class="cookie-slot-name">${cookie.name}</span>`}container.appendChild(slot)}}
function selectBuildBox(button){buildBoxSizeOptions.querySelectorAll(".box-size-card").forEach(c=>c.classList.remove("is-selected"));button.classList.add("is-selected");buildBoxSize=Number(button.dataset.boxSize);buildBoxName=button.dataset.boxName;buildSelection=[];buildSelectedBoxName.textContent=buildBoxName;buildSelectedCount.textContent="0";buildBoxCapacity.textContent=String(buildBoxSize);buildBoxHelper.textContent=`Pick ${buildBoxSize} cookies to complete your ${buildBoxName}.`;openFlavourSelector.disabled=false;renderCookieSlots(buildCookieSlots,buildBoxSize,buildSelection)}
const getBuildQuantity=id=>buildSelection.filter(x=>x===id).length;
function addBuildCookie(id){if(buildSelection.length<buildBoxSize){buildSelection.push(id);updateFlavourSelector()}}
function removeBuildCookie(id){const i=buildSelection.lastIndexOf(id);if(i!==-1){buildSelection.splice(i,1);updateFlavourSelector()}}
function renderFlavourList(){flavourNameList.innerHTML="";gookieCatalogue.forEach(c=>{const row=document.createElement("div");row.className="flavour-row";row.innerHTML=`<div class="flavour-row-copy"><strong>${c.name}</strong><small>${c.subtitle}</small></div><div class="quantity-control"><button class="quantity-button" type="button" data-action="remove" aria-label="Remove ${c.name}">−</button><span class="flavour-quantity">${getBuildQuantity(c.id)}</span><button class="quantity-button" type="button" data-action="add" aria-label="Add ${c.name}">+</button></div>`;row.querySelector('[data-action="remove"]').addEventListener("click",()=>removeBuildCookie(c.id));row.querySelector('[data-action="add"]').addEventListener("click",()=>addBuildCookie(c.id));flavourNameList.appendChild(row)})}
function updateFlavourSelector(){flavourSelectedCount.textContent=String(buildSelection.length);flavourBoxCapacity.textContent=String(buildBoxSize);saveFlavourSelection.disabled=buildSelection.length!==buildBoxSize;renderFlavourList();renderCookieSlots(buildCookieSlots,buildBoxSize,buildSelection);buildSelectedCount.textContent=String(buildSelection.length);const r=buildBoxSize-buildSelection.length;buildBoxHelper.textContent=r===0?"Your Gookie box is ready! 🎉":`Pick ${r} more ${r===1?"cookie":"cookies"} to complete your ${buildBoxName}.`}
function openBuildFlavourSelector(){flavourModalTitle.textContent=buildBoxName;updateFlavourSelector();openModal(flavourModal)}
function saveBuildOrder(){if(buildSelection.length!==buildBoxSize)return;currentOrder={type:"Build Your Box",boxName:buildBoxName,boxSize:buildBoxSize,cookies:[...buildSelection]};updateCart();closeModal(flavourModal);openDrawer(cartDrawer,cartButton)}
function renderCollections(){gookieCollections.forEach(col=>{const b=document.createElement("button");b.className="collection-card";b.type="button";b.innerHTML=`<strong>${col.name}</strong><span>${col.description}</span>`;b.addEventListener("click",()=>{collectionGrid.querySelectorAll(".collection-card").forEach(c=>c.classList.remove("is-selected"));b.classList.add("is-selected");selectedCollection=col;gookieChoiceBoxArea.classList.remove("is-hidden");gookieChoicePreview.classList.add("is-hidden")});collectionGrid.appendChild(b)})}
function shuffleArray(v){const a=[...v];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function createGookieChoiceSelection(){if(!selectedCollection||!gookieChoiceSize)return;const pool=selectedCollection.pool;if(pool.length===1)gookieChoiceSelection=Array(gookieChoiceSize).fill(pool[0]);else{let s=[];while(s.length<gookieChoiceSize)s.push(...shuffleArray(pool));gookieChoiceSelection=s.slice(0,gookieChoiceSize)}renderGookieChoicePreview()}
function renderGookieChoicePreview(){gookieChoiceTitle.textContent=`${selectedCollection.name} · ${gookieChoiceSize} Cookies`;renderCookieSlots(gookieChoiceSlots,gookieChoiceSize,gookieChoiceSelection);const counts={};gookieChoiceSelection.forEach(id=>counts[id]=(counts[id]||0)+1);gookieChoiceSummary.textContent=Object.entries(counts).map(([id,q])=>`${getCookieById(id).name} ×${q}`).join(" · ");gookieChoicePreview.classList.remove("is-hidden")}
function selectGookieChoiceSize(button){gookieChoiceSizeOptions.querySelectorAll(".box-size-card").forEach(c=>c.classList.remove("is-selected"));button.classList.add("is-selected");gookieChoiceSize=Number(button.dataset.boxSize);createGookieChoiceSelection()}
function saveGookieChoiceOrder(){if(!selectedCollection||!gookieChoiceSelection.length)return;const b=gookieChoiceSizeOptions.querySelector(".box-size-card.is-selected");currentOrder={type:"Gookie's Choice",collectionName:selectedCollection.name,boxName:b.dataset.boxName,boxSize:gookieChoiceSize,cookies:[...gookieChoiceSelection]};updateCart();openDrawer(cartDrawer,cartButton)}
function updateCart(){const total=currentOrder?currentOrder.cookies.length:0;cartCount.textContent=String(total);cartSelectedCount.textContent=String(total);if(!currentOrder){cartEmptyState.hidden=false;cartContent.hidden=true;checkoutButton.disabled=true;return}cartEmptyState.hidden=true;cartContent.hidden=false;checkoutButton.disabled=false;const counts={};currentOrder.cookies.forEach(id=>counts[id]=(counts[id]||0)+1);const summary=Object.entries(counts).map(([id,q])=>{const c=getCookieById(id);return `<div class="cart-summary-item"><strong>${c.name} ×${q}</strong><span>${c.subtitle}</span></div>`}).join("");cartOrderSummary.innerHTML=`<div class="cart-summary-item"><strong>${currentOrder.type}</strong><span>${currentOrder.collectionName||currentOrder.boxName}</span></div><div class="cart-summary-item"><strong>${currentOrder.boxName}</strong><span>${currentOrder.boxSize} cookies</span></div>${summary}`}
menuButton.addEventListener("click",()=>openDrawer(menuDrawer,menuButton));cartButton.addEventListener("click",()=>openDrawer(cartDrawer,cartButton));menuCloseButton.addEventListener("click",()=>closeDrawer(menuDrawer));cartCloseButton.addEventListener("click",()=>closeDrawer(cartDrawer));pageOverlay.addEventListener("click",()=>{closeAllDrawers();closeAllModals();resumeMarquee()});cookieModalClose.addEventListener("click",()=>closeCookieDetails(true));getYourGookiesButton.addEventListener("click",()=>{closeCookieDetails(false);scrollToSection($("choose-your-way"));setTimeout(resumeMarquee,800)});showBuildYourBox.addEventListener("click",()=>showOrderSection(buildYourBoxSection,gookiesChoiceSection));showGookiesChoice.addEventListener("click",()=>showOrderSection(gookiesChoiceSection,buildYourBoxSection));buildBoxSizeOptions.querySelectorAll(".box-size-card").forEach(b=>b.addEventListener("click",()=>selectBuildBox(b)));openFlavourSelector.addEventListener("click",openBuildFlavourSelector);flavourModalClose.addEventListener("click",()=>closeModal(flavourModal));saveFlavourSelection.addEventListener("click",saveBuildOrder);gookieChoiceSizeOptions.querySelectorAll(".box-size-card").forEach(b=>b.addEventListener("click",()=>selectGookieChoiceSize(b)));reshuffleChoice.addEventListener("click",createGookieChoiceSelection);keepGookieChoice.addEventListener("click",saveGookieChoiceOrder);document.querySelectorAll(".drawer-nav a").forEach(a=>a.addEventListener("click",closeAllDrawers));document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeAllDrawers();closeAllModals();resumeMarquee()}});
renderMarquee();renderCollections();renderCookieSlots(buildCookieSlots,0,[]);updateCart();
